[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# API Routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/authors/*"
  to = "/.netlify/functions/authors/:splat"
  status = 200

[[redirects]]
  from = "/render/*"
  to = "/.netlify/functions/render/:splat"
  status = 200
